#!/usr/bin/env ruby

## LIBS ##
require 'fileutils'
#require 'pathname'

## VARS ##
dir1 = ARGV[0]
dir2 = ARGV[1]
#hidden_files = Dir.glob["**/.*"]
#files = Dir.glob["**/*"]

banner = <<-HEREDOC
    Usage: #{__FILE__} </path/to/source> </path/to/target>

HEREDOC

## FUNCTIONS
def report_location
puts Dir.pwd
end

def go_home
Dir.chdir("#{Dir.home}")
report_location
end

def mkdir(dir)
Dir.mkdir("#{dir}")
report_location
end

## MAIN ##
# does this check work?
puts banner unless ARGV[1].empty?
Dir.glob("#{dir1}/*") { |f| FileUtils.cp File.expand_path(f), "#{dir2}" }

####
#	
#	
#	How can I add "File.expandpath()" ???
#	






