#!/usr/bin/env ruby

require 'tty'

## VARS ##
prompt = TTY::Prompt.new

editors = %w[vim neovim emacs]
terminals = %w[konsole termite xterm]
images = %w[nitrogen feh sxiv]
bars = %w[lemonbar-xft-git polybar-git i3blocks]
finders = %w[dmenu rofi-git j4-dmenu-desktop albert]
compositors = %w[xcompmgr compton-git compiz]
browsers = %w[qutebrowser-git firefox opera]

## METHODS ##
def install(package)
  `pacaur -S --noconfirm --noedit #{package}`
end

## MAIN ##
result = prompt.collect do
key(:editor).multi_select("Choose an editor", editors)
key(:terminal).multi_select("Choose a termianl", terminals)
key(:image).multi_select("Choose an image viewer", images)
key(:bar).multi_select("Choose a bar", bars)
key(:finder).multi_select("Choose a finder", finders)
key(:compositor).multi_select("Choose a compositor", compositors)
key(:browser).multi_select("Choose a browser", browsers)
end

result.each_value do |value|
  package = value.to_s.gsub(/[\[\]]/, "")
  install(package)
end

