#!/usr/bin/env ruby

def calculate
prompt = <<EOF
Please type in the math operation you would like to complete:
+ for addition
- for subtraction
* for multiplication
/ for division
EOF

puts prompt
operation = gets.chomp

puts "Enter your first number: "
number_1 = gets.chomp.to_i

puts "Enter your second number "
number_2 = gets.chomp.to_i

case operation
when "+"
  puts number_1 + number_2
when "-"
  puts number_1 - number_2
when "*"
  puts number_1 * number_2
when "/"
  puts number_1 / number_2
else
  puts "You have not typed a valid operator, please run the program again."
end
end

# again

calculate
