#!/usr/bin/env ruby

require 'rake'

# Load all tasks in the directory '.rake' with the extension '.rake'
# ~/.rake/{clean.rake, blog.rake, system.rake}
Dir.glob(".rake/**.rake").each { |f| import f }

task :default => 'blog.html'

file 'blog.html' do
File.open('blog.html', 'a+') do |f|
html = <<-EOS
<!DOCTYPE html>
<head>
<title>Rake Essentials</title>
</head>
<html>
<body>
<a href="#">Content</a>
</body>
</html>
EOS
f.write(html)
end
end
