def print_banner
  puts "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
  puts "┃░█▀▄░█▀█░▀█▀░█▀▀░▀█▀░█░░░█▀▀░█▀▀░┃"
  puts "┃░█░█░█░█░░█░░█▀▀░░█░░█░░░█▀▀░▀▀█░┃"
  puts "┃░▀▀░░▀▀▀░░▀░░▀░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░┃"
  puts "┠━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫"
  puts "┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃"
  puts "┃░░ Install script for mjturt's ░░┃"
  puts "┃░░ dotfiles.                   ░░┃"
  puts "┃░░ Do not recommended to use.  ░░┃"
  puts "┃░░ Basic setup:                ░░┃"
  puts "┃░░ ./install.sh commons        ░░┃"
  puts "┃░░ ./install.sh host_r5        ░░┃"
  puts "┃░░ ./install.sh -h to get help ░░┃"
  puts "┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░┃"
  puts "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"

  puts "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
  puts "┃ Annoying starting animation ┃"
  puts "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛"

  puts "\e[1;34mＩ\e[0m"
  puts "\e[1;34mＩＮ\e[0m"
  puts "\e[1;34mＩＮＳ\e[0m"
  puts "\e[1;34mＩＮＳＴ\e[0m"
  puts "\e[1;34mＩＮＳＴＡ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳＣ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳＣＲ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳＣＲＩ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳＣＲＩＰ\e[0m"
  puts "\e[1;34mＩＮＳＴＡＬＬ\e[1;35mＳＣＲＩＰＴ\e[0m"
end
